//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gti_sistema_cliente_database_context : DbContext
    {
       
        public gti_sistema_cliente_database_context()
            : base(ConfigurationManager.ConnectionStrings["gti_sistema_cliente_database_context"].ConnectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_CLIENTE> TB_CLIENTE { get; set; }
        public virtual DbSet<TB_CLIENTE_DOCUMENTO> TB_CLIENTE_DOCUMENTO { get; set; }
        public virtual DbSet<TB_CLIENTE_ENDERECO> TB_CLIENTE_ENDERECO { get; set; }
        public virtual DbSet<TB_ESTADO_CIVIL> TB_ESTADO_CIVIL { get; set; }
        public virtual DbSet<TB_ORGAO_EXPEDIDOR> TB_ORGAO_EXPEDIDOR { get; set; }
        public virtual DbSet<TB_SEXO> TB_SEXO { get; set; }
        public virtual DbSet<TB_UNIDADE_FEDERATIVA> TB_UNIDADE_FEDERATIVA { get; set; }
    }
}
