//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CLIENTE_ENDERECO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CLIENTE_ENDERECO()
        {
            this.TB_CLIENTE = new HashSet<TB_CLIENTE>();
        }
    
        public int ID_CLTE_ENDCO { get; set; }
        public string NM_LOGRADOURO_CLTE_ENDCO { get; set; }
        public string NM_NUMERO_CLTE_ENDCO { get; set; }
        public string NM_CEP_CLTE_ENDCO { get; set; }
        public string NM_COMPLEMENTO_CLTE_ENDCO { get; set; }
        public string NM_BAIRRO_CLTE_ENDCO { get; set; }
        public string NM_CIDADE_CLTE_ENDCO { get; set; }
        public int TB_UNIDADE_FEDERATIVA_ID_UNIDE_FEDA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CLIENTE> TB_CLIENTE { get; set; }
        public virtual TB_UNIDADE_FEDERATIVA TB_UNIDADE_FEDERATIVA { get; set; }
    }
}
