//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CLIENTE
    {
        public int ID_CLIENTE { get; set; }
        public string NM_NOME { get; set; }
        public string NM_CPF { get; set; }
        public System.DateTime DT_NASCIMENTO { get; set; }
        public int TB_CLIENTE_DOCUMENTO_ID_DOCUMENTO { get; set; }
        public int TB_CLIENTE_ENDERECO_ID_CLTE_ENDCO { get; set; }
        public int TB_SEXO_ID_SEXO { get; set; }
        public int TB_ESTADO_CIVIL_ID_ESTD_CIVIL { get; set; }
    
        public virtual TB_CLIENTE_DOCUMENTO TB_CLIENTE_DOCUMENTO { get; set; }
        public virtual TB_CLIENTE_ENDERECO TB_CLIENTE_ENDERECO { get; set; }
        public virtual TB_ESTADO_CIVIL TB_ESTADO_CIVIL { get; set; }
        public virtual TB_SEXO TB_SEXO { get; set; }
    }
}
