//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ORGAO_EXPEDIDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ORGAO_EXPEDIDOR()
        {
            this.TB_CLIENTE_DOCUMENTO = new HashSet<TB_CLIENTE_DOCUMENTO>();
        }
    
        public int ID_ORGAO_EXPEDIDOR { get; set; }
        public string ST_ORGAO_EXPDOR { get; set; }
        public string NM_ORGAO_EXPDOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CLIENTE_DOCUMENTO> TB_CLIENTE_DOCUMENTO { get; set; }
    }
}
